name: get_x
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  iconsax_flutter: ^1.0.0 #A Flutter package for Iconsax Icons.
  intl: ^0.19.0
  dio: ^5.4.0  # Ensure you have the latest version
  pretty_dio_logger: ^1.3.1  # For logging API requests (optional)
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_storage: ^2.1.1 #A fast, extra light and synchronous key-value in memory, which backs up data to disk at each operation. It is written entirely in Dart and easily integrates with Get framework of Flutter.
  connectivity_plus: ^5.0.2 #This plugin allows Flutter apps to discover network connectivity types that can be used.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic